language: ruby
cache: bundler
sudo: false
services:
  - redis-server
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode
env:
  - USE_REAL_REDIS=true
gemfile:
  - gemfiles/redis_3.gemfile
  - gemfiles/redis_4.gemfile
script:
  - bundle exec rspec